### ISSUE TITLE
Markdown的简单语法

### ISSUE THREAD

**Issue by chenxi916** [chenxi916/chenxi#1]
# Markdown的简单语法

### 1.标题

*   使用 `#` 表示标题，一级标题使用一个 `#` ，二级标题使用两个 `##` ，以此类推，共有六级标题。
*   使用 `=====` 表示高阶标题，使用 `---------` 表示次阶标题。

1.  `#` 和标题之间记得有个空格哦。
2.  `====` 和 `----` 表示标题时，大于等于2个都可以表示。

### 2.引用

使用 `>` 表示引用， `>>` 表示引用里面再套一层引用，依次类推。

1.  如果 `>` 和 `>>` 嵌套使用的话，从 `>>` 退到 `>` 时，必须之间要加一个空格或者 `>` 作为过渡，否则默认为下一行和上一行是同一级别的引用。如示例所示。
2.  引用标记里可以使用其他标记，如：有序列表或无序列表标记，代码标记等。

示例

> 这是一级引用
> >这是二级引用
> >
> >> 这是三级引用

>这是一级引用

### 3 代码块

使用3个连续的` 符号包围起来表示代码块。

1.  本文档所有使用讲解Markdown语法标记示例的地方都是使用代码块标记的。
2. 代码块前后都得有换行哦

示例

```javascript
$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
```

### 4 行内代码

使用``表示行内代码。本页部分文字中间的英文字母就是使用行内代码标记标记的。

示例

这是 `javascript` 代码

### 5 链接

使用 `[](link)` 表示行内链接。其中：

*   `[]` 内的内容为要添加链接的文字。
*   `link` 为链接地址。

示例

我觉得[Markdown](https://apps.apple.com/app/id1472328263)真是个棒棒哒的编辑器😊.

### 6 数学公式

`$`包围的区块将会解析为数学公式，连续的`$$`将独占一行并居中显示

示例

当 $a \ne 0$, 此方程式有两个解 $ax^2 + bx + c = 0$，他们是 

$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

### 7 导入图片

使用 `![Alt text](/path/to/img.jpg)` 导入图片。其中：

*   `Alt text` 为如果图片无法显示时显示的文字；
*   `/path/to/img.jpg` 为图片所在路径；

点击辅助键盘中的添加图片按钮可快捷添加图片
1. ==本地引用==是图片直接存储到本地通过相对路径引用，无需网络连接
2. ==上传图片==将把图片上传至图床，这样在文档或图片移动时仍然可以访问图片
[链接标题]()
示例。

![Markdown](https://i.loli.net/2020/03/14/I8wCZN4r9UltqTd.jpg)

### 8 Todo List

小写x表示已完成， 空格表示未完成

- [x] 支持数学公式
- [x] 支持TodoList
- [x] 支持自定义样式
- [ ] 支持自定义图床

### 9 粗体，斜体，高亮和删除线

1. 使用 `**` 或者 `__` 表示**粗体**。
2. 使用 `*` 或者 `_` 表示*斜体*。
3. 使用`==`表示==高亮==
4. 使用`~~`表示~~删除~~
5. `*`，`=` 或 `_` 的后面**不要跟空格哦**

### 10 列表

使用 `1. 2. 3.` 表示有序列表，使用 `*` 或 `-` 或 `+` 表示无序列表。

1.  无序列表或有序列表标记和后面的文字之间要有一个空格隔开。
2.  有序列表标记不是按照你写的数字进行显示的，而是根据当前有序列表标记所在位置显示的，如示例1所示。
3.  无序列表的项目符号是按照实心圆、空心圆、实心方格的层级关系递进的，如例2所示。通常情况下，同一层级使用同一种标记表示，便于自己查看和管理。

#### 例1：有序列表

1.  第一点
2.  第二点
4.  第三点

#### 例2：无序列表

+ 一级无序列表内容

	* 二级无序列表内容
	- 二级无序列表内容
		- 三级无序列表内容
		- 三级无序列表内容
+ 一级无序列表内容

	- 二级无序列表内容

### 11 分割线

使用 `---` 或者 `***` 或者 `* * *` 表示水平分割线。

1.  只要 `*` 或者 `-` 大于等于三个就可组成一条平行线。
2.  使用 `---` 作为水平分割线时，要在它的前后都空一行，防止 `---` 被当成标题标记的表示方式。

示例

---

***

* * *

### 12表格

上面空一行下面空两行：`---|---`

Heading | Heading | Heading
------- | ------- | -------
Cell   |  Cell   |  Cell
Cell   |  Cell   |  Cell

添加边框：`|`

| Heading | Heading | Heading |
| ------- | ------- | ------- |
|   Cell  |   Cell  |   Cell  |
|   Cell  |   Cell  |   Cell  |

对齐方式：==左对齐==`:---`  ==居中==`:---:`==右对齐== `---:`

Heading | Heading | Heading
:----- | :----: | ------:
Left   | Center | Right
Left   | Center | Right

**Comment by chenxi916** [comment]
# 标题

要创建标题，请在标题文本前添加一至六个 # 符号。 你使用的 # 数量将决定层次结构级别和标题的大小。

```
# A first-level heading
## A second-level heading
### A third-level heading
```

# A first-level heading
## A second-level heading
### A third-level heading


使用两个或多个标题时，GitHub 会自动生成一个目录，可以通过单击文件标题中的`三`来访问该目录。 每个标题都列在目录中，可以单击某个标题导航到所选部分。

# 文本样式

可以在评论字段和`.md`文件中以粗体、斜体、删除线、下标或上标文本表示强调。


Style | 语法 | 键盘快捷键 |	示例	| 输出
--     | --   | --          | --    | -- 
加粗   | `** **` 或 `__ __` | `Command`+`B` (Mac) 或 `Ctrl`+`B` (Windows/Linux)	| `**This is bold text**` | **这是粗体文本**
斜体   | `* *` 或 `_ _`  | `Command`+`I` (Mac) 或 `Ctrl`+`I`(Windows/Linux)	| `_This text is italicized_` | _这是斜体文本_
删除线 | `~~　~~`	| 无 |　`~~This was mistaken text~~` | ~~这是错误文本~~
粗体和嵌入的斜体 | `** **` 和 `_ _` | 无	| `**This text is _extremely_ important**` | **此文本 _非常_ 重要**
全部粗体和斜体 | *** ***	| 无 |　`***All this text is important***` | ***所有这些文本都很重要***
下标 |	`<sub> </sub>` | 无 | `This is a <sub>subscript</sub> text`	| 这是<sub>下标</sub>文本
上标 |	`<sup> </sup>` | 无 | `This is a <sup>superscript</sup> text` | 这是<sup>上标</sup>文本

# 引用文本

可以使用 `>` 来引用文本。

```
Text that is not a quote

> Text that is a quote
```

Text that is not a quote

> Text that is a quote

>引用文本缩进，具有不同的类型颜色。

# 引用代码

使用单反引号可标注句子中的代码或命令。 反引号中的文本不会被格式化。 你也可以按 `Command`+`E` (Mac) 或 `Ctrl`+`E` (Windows/Linux) 键盘快捷方式将代码块的反引号插入到 Markdown 一行中。

```Use `git status` to list all new or modified files that haven't yet been committed.```

Use `git status` to list all new or modified files that haven't yet been committed.

要将代码或文本格式化为各自的不同块，请使用三反引号。

Some basic Git commands are:

```
git status
git add
git commit
```

# 链接

通过将链接文本用方括号` [ ] `括起来，然后将 URL 用括号` ( ) `括起来，可创建内联链接。 还可以使用键盘快捷方式 `Command`+`K` 创建链接。 选择文本后，可以粘贴剪贴板中的 URL 以自动从所选内容创建链接。

还可以通过突出显示文本并使用键盘快捷方式 `Command`+`V` 创建 Markdown 超链接。 如果要将文本替换为链接，请使用键盘快捷方式 `Command`+`Shift`+`V`。

```This site was built using [GitHub Pages](https://pages.github.com/).```

This site was built using [GitHub Pages](https://pages.github.com/).

# 图像

通过添加 `!` 并 将 `alt` 文本用`[ ]` 括起来，可显示图像。 替换文字是等效于图像中信息的短文本。 然后将图像的链接用括号 `()` 括起来。

```![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://myoctocat.com/assets/images/base-octocat.svg)```

![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://myoctocat.com/assets/images/base-octocat.svg)

GitHub 支持将图像嵌入到议题、拉取请求、讨论、评论和 `.md` 文件中。 您可以从仓库显示图像、添加在线图像链接或上传图像。

> 注意：想要显示存储库中的图像时，请使用相对链接而不是绝对链接。

下面是一些使用相对链接显示图像的示例。


上下文	| 相对链接
-- | --
在同一分支的 `.md` 文件中	| `/assets/images/electrocat.png`
在另一个分支的 `.md` 文件中	| `/../main/assets/images/electrocat.png`
在仓库的议题、拉取请求和评论中	| `../blob/main/assets/images/electrocat.png?raw=true`
在另一个存储库的 `.md` 文件中	| `/../../../../github/docs/blob/main/assets/images/electrocat.png`
在另一个仓库的议题、拉取请求和评论中	| `../../../github/docs/blob/main/assets/images/electrocat.png?raw=true`

>注意：上表中的最后两个相对链接只有在查看者至少对包含这些图像的专用存储库具有读取访问权限时，才可用于专用存储库中的图像。

# 列表

可通过在一行或多行文本前面加上 `-`、`*` 或 `+` 来创建一个无序列表。

```
- George Washington
* John Adams
+ Thomas Jefferson
```

- George Washington
* John Adams
+ Thomas Jefferson

要对列表排序，请在每行前面添加一个编号。

```
1. James Madison
2. James Monroe
3. John Quincy Adams
```

1. James Madison
2. James Monroe
3. John Quincy Adams

# 嵌套列表

通过在一个列表项下面缩进一个或多个其他列表项，可创建嵌套列表。

若要使用 GitHub 上的 Web 编辑器或使用等宽字体的文本编辑器（例如 Visual Studio Code）创建嵌套列表，可以直观地对齐列表。 在嵌套列表项的前面键入空格字符，直至列表标记字符（`-` 或 `*`）位于其上方条目中第一个文本字符的正下方。
```
1. First list item
   - First nested list item
     - Second nested list item
```

1. First list item
   - First nested list item
     - Second nested list item

>注意：在基于 Web 的编辑器中，可以先突出显示所需的行，然后分别使用 `Tab` 或 `Shift+Tab` 来缩进或取消缩进一行或多行文本。


# 任务列表
若要创建任务列表，请在列表项前加连字符和空格，后接 `[ ]`。 要将任务标记为完成，请使用 `[x]`。

```
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:
```

- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:

如果任务列表项说明以括号开头，则需要使用 `\` 进行转义：

```
- [ ] \(Optional) Open a followup issue
```

- [ ] \(Optional) Open a followup issue

# 段落

通过在文本行之间留一个空白行，可创建新段落。

#脚注

您可以使用此括号语法为您的内容添加脚注：

```
Here is a simple footnote[^1].

A footnote can also have multiple lines[^2].

[^1]: My reference.
[^2]: To add line breaks within a footnote, prefix new lines with 2 spaces.
  This is a second line.
```

Here is a simple footnote[^1].

A footnote can also have multiple lines[^2].

[^1]: My reference.
[^2]: To add line breaks within a footnote, prefix new lines with 2 spaces.
  This is a second line.

> 注意：Markdown 中脚注的位置不会影响该脚注的呈现位置。 您可以在引用脚注后立即写脚注，脚注仍将呈现在 Markdown 的底部。



# 警报

警报是基于块引用语法的 Markdown 扩展，可用于强调关键信息。 在 GitHub 上，它们以独特的颜色和图标显示，以指示内容的显著性。

只有在对用户成功至关重要时才使用警报，并将每篇文章的警报限制在一到两个，以防止读者负担过重。 此外，应避免连续发出警报。 警报无法嵌套在其他元素中。

要添加警报，请使用指定警报类型的特殊块引用行，然后在标准块引用中添加警报信息。 可以使用以下五种类型的警报：


```
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

# 忽略 Markdown 格式

通过在 Markdown 字符前面输入 `\`，可指示 GitHub 忽略 Markdown 格式（或对其进行转义）。

Let's rename \*our-new-project\* to \*our-old-project\*.
